<?php

declare(strict_types=1);

namespace ScottOffen\MarkdownConverter;

/**
 * The names that `:name:` shortcodes can use, such as `:tada:`, and the
 * character each one stands for.
 *
 * The names are the ones that GitHub, GitLab, and Gitea share. The list
 * includes only common names. To add others, use the `customEmoji` setting.
 */
final class Emoji
{
    /**
     * @var array<int|string, string> Maps each name to its character. PHP
     *     converts names that are whole numbers, such as `100` and `-1`, to
     *     integer keys.
     */
    public const NAMES = [
        'smile' => "\u{1F604}",
        'smiley' => "\u{1F603}",
        'grinning' => "\u{1F600}",
        'laughing' => "\u{1F606}",
        'sweat_smile' => "\u{1F605}",
        'joy' => "\u{1F602}",
        'wink' => "\u{1F609}",
        'blush' => "\u{1F60A}",
        'heart_eyes' => "\u{1F60D}",
        'sunglasses' => "\u{1F60E}",
        'thinking' => "\u{1F914}",
        'neutral_face' => "\u{1F610}",
        'confused' => "\u{1F615}",
        'worried' => "\u{1F61F}",
        'cry' => "\u{1F622}",
        'sob' => "\u{1F62D}",
        'scream' => "\u{1F631}",
        'angry' => "\u{1F620}",
        'rage' => "\u{1F621}",
        'sleeping' => "\u{1F634}",
        'pray' => "\u{1F64F}",
        'clap' => "\u{1F44F}",
        '+1' => "\u{1F44D}",
        'thumbsup' => "\u{1F44D}",
        '-1' => "\u{1F44E}",
        'thumbsdown' => "\u{1F44E}",
        'wave' => "\u{1F44B}",
        'ok_hand' => "\u{1F44C}",
        'raised_hands' => "\u{1F64C}",
        'muscle' => "\u{1F4AA}",
        'eyes' => "\u{1F440}",
        'tada' => "\u{1F389}",
        'confetti_ball' => "\u{1F38A}",
        'sparkles' => "\u{2728}",
        'star' => "\u{2B50}",
        'star2' => "\u{1F31F}",
        'fire' => "\u{1F525}",
        'boom' => "\u{1F4A5}",
        'zap' => "\u{26A1}",
        'rocket' => "\u{1F680}",
        'bug' => "\u{1F41B}",
        'beetle' => "\u{1F41E}",
        'wrench' => "\u{1F527}",
        'hammer' => "\u{1F528}",
        'hammer_and_wrench' => "\u{1F6E0}\u{FE0F}",
        'gear' => "\u{2699}\u{FE0F}",
        'lock' => "\u{1F512}",
        'unlock' => "\u{1F513}",
        'key' => "\u{1F511}",
        'shield' => "\u{1F6E1}\u{FE0F}",
        'warning' => "\u{26A0}\u{FE0F}",
        'no_entry' => "\u{26D4}",
        'no_entry_sign' => "\u{1F6AB}",
        'x' => "\u{274C}",
        'heavy_check_mark' => "\u{2714}\u{FE0F}",
        'white_check_mark' => "\u{2705}",
        'question' => "\u{2753}",
        'exclamation' => "\u{2757}",
        'bangbang' => "\u{203C}\u{FE0F}",
        'information_source' => "\u{2139}\u{FE0F}",
        'bulb' => "\u{1F4A1}",
        'memo' => "\u{1F4DD}",
        'book' => "\u{1F4D6}",
        'books' => "\u{1F4DA}",
        'bookmark' => "\u{1F516}",
        'link' => "\u{1F517}",
        'paperclip' => "\u{1F4CE}",
        'package' => "\u{1F4E6}",
        'art' => "\u{1F3A8}",
        'lipstick' => "\u{1F484}",
        'construction' => "\u{1F6A7}",
        'rotating_light' => "\u{1F6A8}",
        'recycle' => "\u{267B}\u{FE0F}",
        'wastebasket' => "\u{1F5D1}\u{FE0F}",
        'arrow_up' => "\u{2B06}\u{FE0F}",
        'arrow_down' => "\u{2B07}\u{FE0F}",
        'arrow_right' => "\u{27A1}\u{FE0F}",
        'arrow_left' => "\u{2B05}\u{FE0F}",
        'hourglass' => "\u{231B}",
        'calendar' => "\u{1F4C5}",
        'chart_with_upwards_trend' => "\u{1F4C8}",
        'chart_with_downwards_trend' => "\u{1F4C9}",
        'bar_chart' => "\u{1F4CA}",
        'mag' => "\u{1F50D}",
        'bell' => "\u{1F514}",
        'mega' => "\u{1F4E3}",
        'email' => "\u{1F4E7}",
        'speech_balloon' => "\u{1F4AC}",
        'heart' => "\u{2764}\u{FE0F}",
        'broken_heart' => "\u{1F494}",
        '100' => "\u{1F4AF}",
        'trophy' => "\u{1F3C6}",
        'gift' => "\u{1F381}",
        'coffee' => "\u{2615}",
        'beer' => "\u{1F37A}",
        'pizza' => "\u{1F355}",
        'seedling' => "\u{1F331}",
        'sunny' => "\u{2600}\u{FE0F}",
        'snowflake' => "\u{2744}\u{FE0F}",
        'globe_with_meridians' => "\u{1F310}",
        'computer' => "\u{1F4BB}",
        'iphone' => "\u{1F4F1}",
        'floppy_disk' => "\u{1F4BE}",
        'battery' => "\u{1F50B}",
        'electric_plug' => "\u{1F50C}",
        'truck' => "\u{1F69A}",
        'ambulance' => "\u{1F691}",
        'see_no_evil' => "\u{1F648}",
        'poop' => "\u{1F4A9}",
        'ghost' => "\u{1F47B}",
        'skull' => "\u{1F480}",
        'robot' => "\u{1F916}",
        'alien' => "\u{1F47D}",
        'unicorn' => "\u{1F984}",
        'dog' => "\u{1F436}",
        'cat' => "\u{1F431}",
    ];
}
